name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
        dependencies: ['lowest', 'highest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies (lowest)
        run: composer update --prefer-lowest --no-interaction --no-progress --ansi

      - name: Install dependencies (highest)
        run: composer update --no-interaction --no-progress --ansi

      - name: Check code-style
        run: composer php-cs-fixer-lint

      - name: Run tests
        run: composer run test
